version: 2.1

executors:
  ruby-executor:
    docker:
      - image: cimg/ruby:2.7.6
        environment:
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3

jobs:
  rspec:
    executor: ruby-executor
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "Gemfile.lock" }}
            - v1-dependencies-
      - run:
          name: Install dependencies
          command: bundle install --path vendor/bundle
      - save_cache:
          paths:
            - vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
      - run:
          name: Run RSpec
          command: bundle exec rspec

workflows:
  version: 2
  test:
    jobs:
      - rspec
